#	$NetBSD: Makefile,v 1.1.1.3 2008/11/11 19:32:32 joerg Exp $

OBJ=lstAppend.o lstDupl.o lstInit.o lstOpen.o lstAtEnd.o lstEnQueue.o \
    lstInsert.o lstAtFront.o lstIsAtEnd.o lstClose.o lstFind.o lstIsEmpty.o \
    lstRemove.o lstConcat.o lstFindFrom.o lstLast.o lstReplace.o lstFirst.o \
    lstDatum.o lstForEach.o lstMember.o lstSucc.o lstDeQueue.o \
    lstForEachFrom.o lstDestroy.o lstNext.o lstPrev.o

CPPFLAGS=-I${.CURDIR}/..
all: ${OBJ}
