# $NetBSD: Makefile.common,v 1.1.1.1 2001/07/08 17:26:57 mjl Exp $

VERSION=	0.0.6
DISTNAME=	ruby-dbi-all-${VERSION}
CATEGORIES=	databases
MASTER_SITES=	http://www.ruby-projects.org/downloads/dbi/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.ruby-projects.org/dbi/

WRKSRC=		${WRKDIR}/ruby-dbi-all

do-build:
	cd ${WRKSRC}; ${RUBY} setup.rb setup

do-install:
	cd ${WRKSRC}; ${RUBY} setup.rb install

.include "../../lang/ruby-base/Makefile.common"
.include "../../mk/bsd.pkg.mk"
