# $NetBSD: Makefile,v 1.1.1.2 2006/10/02 19:14:13 rillig Exp $
#

DISTNAME=	Carp-Clan-5.4
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.cpan.org/pub/CPAN/modules/by-module/Carp/

MAINTAINER=	rillig@NetBSD.org
HOMEPAGE=	ftp://ftp.cpan.org/pub/CPAN/modules/by-module/Carp/
COMMENT=	Advanced error reporting for Perl

PERL5_PACKLIST=	auto/Carp/Clan/.packlist
USE_LANGUAGES=	# none

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
