# $NetBSD: Makefile,v 1.1.1.2 2001/03/12 11:46:36 zuntum Exp $

DISTNAME=	gone-1.3.1
CATEGORIES=	misc
MASTER_SITES=	http://jaguar.ir.miami.edu/~marcus/

MAINTAINER=	zuntum@netbsd.org
HOMEPAGE=	http://jaguar.ir.miami.edu/~marcus/
COMMENT=	Terminal locking utility with many improvements over lock(1)

GNU_CONFIGURE=	yes

CONFIGURE_ENV=	with_setuid=no

.include "../../mk/bsd.pkg.mk"
