# $NetBSD: buildlink3.mk,v 1.1 2004/05/11 04:01:39 snj Exp $

.include "../../lang/python/pyversion.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PYMETAR_BUILDLINK3_MK:=	${PYMETAR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pymetar
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npymetar}
BUILDLINK_PACKAGES+=	pymetar

.if !empty(PYMETAR_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.pymetar+=	pymetar-[0-9]*
BUILDLINK_PKGSRCDIR.pymetar?=	../../net/py-METAR
.endif	# PYMETAR_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
