# $NetBSD: Makefile,v 1.1.1.1 2000/12/30 20:04:25 rh Exp $
#

DISTNAME=	${PKGNAME:S/-//}
PKGNAME=	sslwrap-206
CATEGORIES=	security net
MASTER_SITES=	http://www.rickk.com/sslwrap/

MAINTAINER=	rh@netbsd.org
HOMEPAGE=	http://www.rickk.com/sslwrap/

DEPENDS+=	openssl>=0.9.4:../../security/openssl

.include "../../mk/bsd.pkg.mk"
