#	$NetBSD: Makefile,v 1.1.1.4 2015/05/19 21:36:44 joerg Exp $
#	@(#)Makefile	8.1 (Berkeley) 8/14/93

SECTION=reference/ref1
ARTICLE=make
SRCS=	tutorial.ms
MACROS=	-ms
EXTRAHTMLFILES=make1.png make2.png

.include <bsd.doc.mk>
